### PR TITLE
Express, package.json, no more sync

### PR DESCRIPTION
**Pull request by aurieh**

### CODE REVIEW

**Review by adenflorian — APPROVED** [review]
This is great!

**Comment by adenflorian** [comment]
@aurieh Thanks for this! Sorry it took me so long to see it, will get it live in a few minutes.

**Comment by adenflorian** [comment]
@aurieh It's live! https://random.dog/woof.json

**Comment by adenflorian** [comment]
@aurieh I'm not sure if I did something wrong, you don't show up on the contributors graph, I wonder if it takes a little while?

**Comment by aurieh** [comment]
Probably, thanks for deploying!

**Pull request merged**
